name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ioncretu809/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ioncretu809/react-test npm test

      - run: docker build -t ioncretu809/multi-client ./client
      - run: docker build -t ioncretu809/multi-nginx ./nginx
      - run: docker build -t ioncretu809/multi-server ./server
      - run: docker build -t ioncretu809/multi-worker ./worker

      - run: docker push ioncretu809/multi-client
      - run: docker push ioncretu809/multi-nginx
      - run: docker push ioncretu809/multi-server
      - run: docker push ioncretu809/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      

      